  
export const AuthActionTypes = {
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  SOCIAL_LOGIN_START: " SOCIAL_LOGIN_START",
  SOCIAL_LOGIN_SUCCESS: " SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAIL: " SOCIAL_LOGIN_FAIL",

  GET_USER_START: " GET_USER_START",
  GET_USER_SUCCESS: " GET_USER_SUCCESS",
  GET_USER_FAIL: " GET_USER_FAIL",

  UPDATE_USER_IMAGE_START: " UPDATE_USER_IMAGE_START",
  UPDATE_USER_IMAGE_SUCCESS: " UPDATE_USER_IMAGE_SUCCESS",
  UPDATE_USER_IMAGE_FAIL: " UPDATE_USER_IMAGE_FAIL",
};
export const ModlasActionTypes = {
  SHOW_ADD_POST_MODAL: "SHOW_ADD_POST_MODAL",
};
export const PostActionTypes = {

  CREATE_POSTS_START: " CREATE_POSTS_START",
  CREATE_POSTS_SUCCESS: " CREATE_POSTS_SUCCESS",
  CREATE_POSTS_FAIL: " CREATE_POSTS_FAIL",

};