export const AuthActionTypes = {
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  SOCIAL_LOGIN_START: " SOCIAL_LOGIN_START",
  SOCIAL_LOGIN_SUCCESS: " SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAIL: " SOCIAL_LOGIN_FAIL",

  GET_USER_START: " GET_USER_START",
  GET_USER_SUCCESS: " GET_USER_SUCCESS",
  GET_USER_FAIL: " GET_USER_FAIL",

  UPDATE_USER_IMAGE_START: " UPDATE_USER_IMAGE_START",
  UPDATE_USER_IMAGE_SUCCESS: " UPDATE_USER_IMAGE_SUCCESS",
  UPDATE_USER_IMAGE_FAIL: " UPDATE_USER_IMAGE_FAIL",
};
export const ModlasActionTypes = {
  SHOW_ADD_POST_MODAL: "SHOW_ADD_POST_MODAL",
};
export const PostActionTypes = {
  CREATE_POSTS_START: " CREATE_POSTS_START",
  CREATE_POSTS_SUCCESS: " CREATE_POSTS_SUCCESS",
  CREATE_POSTS_FAIL: " CREATE_POSTS_FAIL",
};
export const SotryiesActionTypes = {
  ADD_STORY_START: " ADD_STORY_START",
  ADD_STORY_SUCCESS: " ADD_STORY_SUCCESS",
  ADD_STORY_FAIL: " ADD_STORY_FAIL",

  GET_STORIES_START: " GET_STORIES_START",
  GET_STORIES_SUCCESS: " GET_STORIES_SUCCESS",
  GET_STORIES_FAIL: " GET_STORIES_FAIL",

  GET_SINGLE_USER_STORIES_START: " GET_SINGLE_USER_STORIES_START",
  GET_SINGLE_USER_STORIES_SUCCESS: " GET_SINGLE_USER_STORIES_SUCCESS",
  GET_SINGLE_USER_STORIES_FAIL: " GET_SINGLE_USER_STORIES_FAIL",

  VIEWED_STORY_START: " VIEWED_STORY_START",
  VIEWED_STORY_SUCCESS: " VIEWED_STORY_SUCCESS",
  VIEWED_STORY_FAIL: " VIEWED_STORY_FAIL",

  UPDATE_LOCAL_STORIES_DATA: " UPDATE_LOCAL_STORIES_DATA",
};
