export { default as Signup } from "./Signup/Signup";
export { default as Login } from "./Login/Login";
export { default as Home } from "./Home/Home";
export { default as Igtv } from "./Igtv/Igtv";
export { default as Profile } from "./Profile/Profile";
export { default as Explore } from "./Explore/Explore";
export { default as Saved } from "./Saved/Saved";
export { default as Modals } from "./Modals";
export { default as Settings } from "./Settings/Settings";
